config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: %i[index show]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
        #get '/representatives/:representative_id/my_news_item/show_articles' => 'my_news_items#show_articles', as: :show_articles_my_news_item
        #match '/representatives/:representative_id/my_news_item/show_articles', to: 'my_news_items#show_articles', via: [:post]
    end

  
    get '/my_news_item/search' => 'my_news_items#search', as: :search_my_news_item
    get '/my_news_item/show_articles' => 'my_news_items#show_articles', as: :show_articles_my_news_item
    match '/representatives/:representative_id/my_news_item/show_articles', to: 'my_news_items#show_articles', via: [:post]
    # post '/my_news_item/save_article' => 'my_news_items#save_article', as: :save_article_my_news_item



    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    get '/show' => 'representatives#show', :as => 'show_representative'
end

app/models/representative.rb
# frozen_string_literal: true

class Representative < ApplicationRecord
  has_many :news_items, dependent: :delete_all
  # serialize :contact_address, Array

  def self.civic_api_to_representative_params(rep_info)
    reps = []

    rep_info.officials.each_with_index do |official, index|
      ocdid_temp = ''
      title_temp = ''

      rep_info.offices.each do |office|
        if office.official_indices.include? index
          title_temp = office.name
          ocdid_temp = office.division_id
        end
      end

      address = official.address&.at(0)
      rep = find_rep(official, ocdid_temp, title_temp, address)

      reps.push(rep)
    end

    reps
  end

  def self.find_rep(official, ocdid, title, address)
    Representative.find_or_create_by!(
      {
        name:            official.name,
        ocdid:           ocdid,
        title:           title,
        address:         address&.line1,
        city:            address&.city,
        state:           address&.state,
        zip:             address&.zip,
        political_party: official.party,
        photo_url:       official.photo_url.present? ? official.photo_url[0] : nil
      }
    )
  end
end

app/controllers/representatives_controller.rb
# frozen_string_literal: true

class RepresentativesController < ApplicationController
  def index
    @representatives = Representative.all
  end

  def show
    index = params[:id]
    @representative = Representative.find(index)
    render :show
  end
end

app/helpers/representatives_helper.rb
# frozen_string_literal: true

module RepresentativesHelper
end

app/views/representatives/index.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Search for a Representative

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag search_representatives_path, method: :get do
            .form-group.row
                .col-md-4
                    %label.col-form-label
                        Enter a location:
                .col-md-6
                    = text_field_tag(:address, nil, class: 'form-control')

            .actions
                = submit_tag 'Search', class: 'btn btn-primary'

app/views/representatives/search.html.haml
.container-fluid
    .row
        .col-md-8.offset-md-2
            .table-responsive-md.pt-5
                %table.table.table-striped.table-hover#events
                    %caption Table of Representatives
                    %thead.thead-dark
                        %tr
                            %th Name
                            %th Office
                            %th Links
                    %tbody
                        - @representatives.each_with_index do |rep, _index|
                            %tr
                                %td= link_to rep.name, representative_path(rep.id)

                                %td= rep.title
                                %td
                                    = link_to representative_news_items_path(rep.id), class: 'btn btn-primary' do
                                        %i.fas.fa-newspaper
                                        News Articles

app/views/representatives/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @representative.name %></title>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1><%= @representative.name %></h1>

        <% if @representative.photo_url.present? %>
          <img src="<%= @representative.photo_url %>" alt="<%= @representative.name %>" class="img-fluid rounded">
        <% end %>


        <div class="table-responsive">
          <table class="table table-striped">
            <tbody>
              <% if @representative.title.present? %>
                <tr>
                  <th>Title</th>
                  <td><%= @representative.title %></td>
                </tr>
              <% end %>

              <% if @representative.address.present? %>
                <tr>
                  <th>Address</th>
                  <td>
                    <%= @representative.address %>, 
                    <%= @representative.city %>, 
                    <%= @representative.state %>, 
                    <%= @representative.zip %>
                  </td>
                </tr>
              <% end %>

              <% if @representative.political_party.present? %>
                <tr>
                  <th>Political Party</th>
                  <td><%= @representative.political_party %></td>
                </tr>
              <% end %>
              <%= link_to "News Articles", representative_news_items_path(@representative.id), class: 'btn btn-primary' %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</body>
</html>