config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: %i[index show]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
        #get '/representatives/:representative_id/my_news_item/show_articles' => 'my_news_items#show_articles', as: :show_articles_my_news_item
        #match '/representatives/:representative_id/my_news_item/show_articles', to: 'my_news_items#show_articles', via: [:post]
    end

  
    get '/my_news_item/search' => 'my_news_items#search', as: :search_my_news_item
    get '/my_news_item/show_articles' => 'my_news_items#show_articles', as: :show_articles_my_news_item
    match '/representatives/:representative_id/my_news_item/show_articles', to: 'my_news_items#show_articles', via: [:post]
    # post '/my_news_item/save_article' => 'my_news_items#save_article', as: :save_article_my_news_item



    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
    get '/show' => 'representatives#show', :as => 'show_representative'
end

app/controllers/my_news_items_controller.rb
# frozen_string_literal: true

require 'news-api'

class MyNewsItemsController < SessionController
  before_action :set_representative
  before_action :set_representatives_list
  before_action :set_news_item, only: %i[edit update destroy]
  before_action :set_issues_list, only: %i[new edit create update]

  def new
    redirect_to search_my_news_item_path(representative_id: @representative)
    @news_item = NewsItem.new
  end

  def edit; end

  def create
    selected_article_index = params[:article_index]
    @news_item = NewsItem.new(news_item_params)
    @news_item.title = params.dig('news_item', selected_article_index, 'title')
    @news_item.link = params.dig('news_item', selected_article_index, 'link')
    @news_item.description = params.dig('news_item', selected_article_index, 'description')
    @news_item.representative_id = params[:representative_id]
    @news_item.issue = params[:news_item][:issue]
    @news_item.rating = params[:rating]
    if @news_item.save
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully created.'
    else
      render :new, error: 'An error occurred when creating the news item.'
    end
  end

  def update
    if @news_item.update(news_item_params)
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully updated.'
    else
      render :edit, error: 'An error occurred when updating the news item.'
    end
  end

  def destroy
    @news_item.destroy
    redirect_to representative_news_items_path(@representative),
                notice: 'News was successfully destroyed.'
  end

  def index
    render :search, error: 'An error occurred when searching for the news item.'
  end

  def search
    @representatives_list = Representative.all.map { |r| [r.name, r.id] }
    @issues_list = ['Free Speech', 'Immigration', 'Terrorism',
                    'Social Security and Medicare', 'Abortion', 'Student Loans', 'Gun Control',
                    'Unemployment', 'Climate Change', 'Homelessness', 'Racism', 'Tax Reform',
                    'Net Neutrality', 'Religious Freedom', 'Border Security', 'Minimum Wage',
                    'Equal Pay']
  end

  def show_articles
    @representative = Representative.find(params[:representative_id])
    @issue = params[:issue]

    newsapi = News.new(Rails.application.credentials[:NEWS_API_KEY])

    articles = newsapi.get_everything(
      q:        "#{@representative.name}+#{@issue}",
      sortBy:   'relevancy',
      page:     1,
      pageSize: 5
    )

    # @articles = articles['articles']
    @articles = articles
  end

  private

  def set_representative
    @representative = Representative.find(
      params[:representative_id]
    )
  end

  def set_representatives_list
    @representatives_list = Representative.all.map { |r| [r.name, r.id] }
  end

  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end

  def set_issues_list
    @issues_list = ['Free Speech', 'Immigration', 'Terrorism',
                    'Social Security and Medicare', 'Abortion', 'Student Loans', 'Gun Control',
                    'Unemployment', 'Climate Change', 'Homelessness', 'Racism', 'Tax Reform',
                    'Net Neutrality', 'Religious Freedom', 'Border Security', 'Minimum Wage',
                    'Equal Pay']
  end

  # Only allow a list of trusted parameters through.
  def news_item_params
    params.require(:news_item).permit(:news, :title, :description, :link, :representative_id, :issue, :rating)
  end
end

app/views/my_news_items/_form.html.haml
= form_for news_item, url: form_url, html: { method: form_method } do |f|
    - if news_item.errors.any?
        .alert.alert-danger
            %h2
                "#{pluralize(news_item.errors.count, 'error')} prohibited this news from being saved:"
            %ul
                - news_item.errors.full_messages.each do |message|
                    %li= message
    .form-group.row
        .col-sm-2
            = label :news_item, :title, 'Title:', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :title, { class: 'form-control', placeholder: 'Brief title of article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :link, 'Link', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :link, { class: 'form-control', placeholder: 'Link to external article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :description, class: 'col-form-label'
        .col-sm-10
            = text_area :news_item, :description, { class: 'form-control',
            placeholder: 'Describe the contents of the article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :representative_id, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :representative_id, representatives_list, { include_blank: true },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :issue, 'Issue', class: 'col-form-label'
        .col-sm-10
            = select :news_item, :issue, issues_list, { include_blank: true },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :rating, 'Rating', class: 'col-form-label'
        .col-sm-10
            = number_field :news_item, :rating, in: 1..5,
            class: 'form-control'
    .actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/my_news_items/edit.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'form', news_item: @news_item,
         form_url: representative_edit_my_news_item_path(representative_id: @representative, id: @news_item),
         form_method: :put,
         representatives_list: @representatives_list,
         issues_list: @issues_list

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_item_path(representative_id: @representative, id: @news_item),
                class: 'mx-1 btn btn-info' do
                    Show article
                    %i.fas.fa-eye
                = link_to representative_news_items_path(@representative), class: 'mx-1 btn btn-info' do
                    View all news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/new.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'form', news_item: @news_item,
        form_url: representative_new_my_news_item_path(@representative),
        form_method: :post,
        representatives_list: @representatives_list,
        issues_list: @issues_list
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_items_path(@representative), class: 'btn btn-info' do
                    View news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/search.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Search for Representative and Issue

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag show_articles_my_news_item_path(@representative), method: :get do
            .form-group
                = label_tag :representative_id, 'Select Representative'
                = select_tag :representative_id, options_for_select(@representatives_list), class: 'form-control'

            .form-group
                = label_tag :issue, 'Select Issue'
                = select_tag :issue, options_for_select(@issues_list), class: 'form-control'

            = submit_tag 'Search', class: 'btn btn-primary'

app/views/my_news_items/show_articles.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Select an Article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = form_tag representative_new_my_news_item_path(@representative), method: :post do
            .field
                %strong Representative:
                = link_to @representative.name, representative_path(@representative)
                = hidden_field_tag 'news_item[representative_id]', @representative.id
                = hidden_field_tag 'news_item[representative_name]', @representative.name

            .field
                %strong Issue:
                = @issue
                = hidden_field_tag 'news_item[issue]', @issue

            - @articles.each_with_index do |article, index|
                .form-check
                    = radio_button_tag 'article_index', index
                    .article-details
                        %strong= article.title
                        %p= article.description
                        %p URL: #{article.url}
                        %label Rating:
                        = number_field_tag "news_item[#{index}][rating]", nil, in: 1..5, class: 'form-control'
                        = hidden_field_tag "news_item[#{index}][title]", article.title
                        = hidden_field_tag "news_item[#{index}][description]", article.description
                        = hidden_field_tag "news_item[#{index}][link]", article.url
                        = hidden_field_tag "news_item[#{index}][representative_id]", @representative.id
                        = hidden_field_tag "news_item[#{index}][representative_name]", @representative.name
                        = hidden_field_tag "news_item[#{index}][issue]", @issue

            = submit_tag 'Save', class: 'btn btn-primary'